{% set conda_name = "tableschema-py" %}
{% set name = "tableschema" %}
{% set version = "1.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4b68da205780b76b2856470bf3603b7ace97bc7b0ed02337429d78c9bb448b13" %}
{% set build = 0 %}

package:
  name: {{ conda_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - tableschema = tableschema.cli:main
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six >=1.9,<2.0
    - click >=3.3,<7.0
    - requests >=2.5,<3.0
    - python-dateutil >=2.4,<3.0
    - jsonschema >=2.5,<3.0
    - unicodecsv >=0.14,<2.0
    - isodate >=0.5.4,<2.0
    - rfc3986 >=1.1.0,<2.0
    - tabulator-py >=1.3,<2.0


test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types

  commands:
    - tableschema --help

about:
  home: https://github.com/frictionlessdata/tableschema-py
  license_file: LICENSE.md
  license: MIT
  license_family: MIT
  summary: 'A utility library for working with Table Schema in Python'
  dev_url: https://github.com/frictionlessdata/tableschema-py

extra:
  recipe-maintainers:
    - pmlandwehr
